name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: byte-forger
          outputs: "dist/github-contribution-grid-snake.svg?color_snake=%23A78BFA&color_dots=%230d1117,%236D28D9,%237C3AED,%23A78BFA,%23DDD6FE&color_empty=%230d1117"

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
